import { Link } from 'react-router-dom';
import LegalPage from '@/components/LegalPage';
import PrivacyConsentBanner from '@/components/PrivacyConsentBanner';

export default function Privacy() {
  return <LegalPage title="Privacy Policy" path="/privacy">
    <PrivacyConsentBanner />
    <p>DigitalStudios.app is operated for customers in India by Zoa Zone Services Pvt Ltd, 376, G3, Road No 82, Film Nagar, Jubilee Hills, Hyderabad, Telangana 500096, India, and for customers outside India by Zoa Zone Services LLC, 1770 Grand Concourse 12A, Bronx, NY 10457, USA. This policy explains how we handle personal data when you visit, register or use the platform.</p>
    <section id="data-collected"><h2 className="text-xl font-semibold">Data we collect</h2><p>We collect account details (name, email, contact information and business details you provide), login and device information (such as IP address and session activity), billing records and transaction references, support communications, and your prompts, uploaded media, generated assets, projects, social connections, campaign content and lead/contact information you choose to store or process through the service.</p></section>
    <section><h2 className="text-xl font-semibold">Why we use it</h2><p>We use this data to create and secure accounts, deliver AI image, video, audio, dubbing and marketing tools, process purchases, provide customer support, prevent fraud, comply with legal and tax obligations, and improve service reliability. Marketing communications are sent where you have opted in or otherwise permitted by law; you can unsubscribe. If you manage contacts or upload someone else's voice or likeness, you must have the required rights and permissions.</p></section>
    <section><h2 className="text-xl font-semibold">Payments and service providers</h2><p>For payments in India made through Cashfree Payments, Cashfree handles payment credentials securely; we never store raw card details or UPI credentials. We retain only payment status, transaction identifiers and accounting records needed to provide the service and resolve disputes. Other available payment processors may be used for payments outside India. To fulfil requests, we share relevant data with hosting, AI-generation, dubbing, communications and payment providers. Uploaded media may be processed in other countries where these providers operate. We do not sell your personal data.</p></section>
    <section><h2 className="text-xl font-semibold">Retention and security</h2><p>Account details, projects and assets are retained while your account is active or until you delete them. On account closure, we delete or anonymise personal data when it is no longer needed, subject to legal, fraud-prevention and dispute obligations; billing and tax records may be kept for up to seven years. Limited backups and service-provider copies are removed on their respective retention schedules. We use access controls and encryption in transit and restrict access to authorised personnel and service providers.</p></section>
    <section><h2 className="text-xl font-semibold">Your rights and Indian data protection</h2><p>In line with the Digital Personal Data Protection Act, 2023 (India) and other applicable laws, you may ask to access information about your data, correct or erase it, withdraw consent where applicable, or raise a grievance. You can contact us to request these actions; we may verify your identity before responding. Withdrawal of consent will not affect processing already lawfully completed, and some records must be retained by law. You may nominate another person to exercise your rights where applicable.</p></section>
    <section><h2 className="text-xl font-semibold">AI processing</h2><p>Prompts and uploaded images, audio and video are sent to the AI services required to generate requested results, including voice-preserving dubbing. Voice and likeness can be sensitive personal data. Do not upload another person's media without the appropriate authorisation. See our <Link to="/terms" className="text-primary underline">Terms & Conditions</Link> for your responsibilities regarding generated content.</p></section>
    <section><h2 className="text-xl font-semibold">Contact and grievances</h2><p>For privacy questions and rights requests, contact <a className="text-primary underline" href="mailto:care@zoazoneservices.com">care@zoazoneservices.com</a>. For India, write to the Grievance Officer, Zoa Zone Services Pvt Ltd, at the same address. We aim to respond to grievances within 48 hours and resolve them within 15 days under the Information Technology Rules, 2021. See <Link to="/contact" className="text-primary underline">Contact Us</Link> for our addresses and hours.</p></section>
    <p>We may update this policy as our services or legal obligations change. Material changes will be reflected here with a new last-updated date.</p>
  </LegalPage>;
}